**TASK:** import numpy

In [1]:
import numpy as np

**TASK:** define vector 'x' with three coordinates

In [2]:
x = np.arange(1,4)
x

array([1, 2, 3])

**TASK:** define (2 x 2) matrix 'A' 


In [3]:
A = np.arange(0, 4).reshape(2, 2)
A

array([[0, 1],
       [2, 3]])

**TASK:** define (2 x 2) matrix 'B'

In [17]:
B = np.arange(4, 8).reshape(2, 2)
B

array([[4, 5],
       [6, 7]])

**TASK:** check the type of 'x'

In [5]:
type(x)

numpy.ndarray

**TASK:** check the type of 'A'

In [6]:
type(A)

numpy.ndarray

**TASK:**  check the shape of 'x'


In [7]:
x.shape

(3,)

**TASK:** check the [shape] of 'A'

In [8]:
A.shape 

(2, 2)

**TASK:** 

In [9]:
def have_same_shape(array_1: np.ndarray, array_2: np.ndarray) -> bool:
    """"
    Define function 'have_same_shape' which checks if two arrays have same shape.

    PARAMS:
        array_1 (numpy.ndarray) - first array
        array_2 (numpy.ndarray) - second array
    RETURN:
        True - if arrays have same shape
        False - if arrays do not have same shape

    Also print 'Arrays must have same shape!' when returning False
    """
    if array_1.shape != array_2.shape: print('Arrays must have same shape!')
    return array_1.shape == array_2.shape


**TASK:** call the function 'have_same_shape' with matrix 'A' and vector 'x' as inputs

In [10]:
have_same_shape(A, x)

Arrays must have same shape!


False

**TASK:**  call the function 'have_same_shape' with matrix 'A' and matrix 'B' as inputs

In [11]:
have_same_shape(A, B)

True

**TASK:** 

In [12]:
def matrix_addition(A: np.ndarray, B: np.ndarray) -> np.ndarray:
    """
    Performs matrix addition value by value.

    PARAMS:
        A (numpy.ndarray) - first array
        B (numpy.ndarray) - second array
    RETURN:
        C (numpy.ndarray) - new A+B array

    In this task do not consider broadcasting.
    Do not forget to check arrays shapes (you can use 'have_same_shape' function defined before)
    """
    if have_same_shape(A, B):
        C = np.zeros(A.shape)
        for row in range(A.shape[0]):
            for column in range(A.shape[1]):
                C[row, column] = A[row, column] + B[row, column]
        return C

**TASK:** call the function 'matrix_addition' with matrix 'A' and matrix 'B' as inputs

In [18]:
matrix_addition(A, B)

array([[ 4.,  6.],
       [ 8., 10.]])

**TASK:** 

In [28]:
def multiple_matrix_addition(lst_of_arr: list) -> np.ndarray:
    """
    Define 'multiple_matrix_adition' function that takes list of arrays as the input and perform array addition

    PARAMS:
    lst_of_arr (list) - list of numpy.ndarrays
    RETURN:
        NEW_ARRAY (numpy.ndarray) - new array

    Use 'matrix_addition' function defined before.
    """
    NEW_ARRAY = np.zeros(lst_of_arr[0].shape)
    for array in lst_of_arr:
        NEW_ARRAY = matrix_addition(array, NEW_ARRAY)
    return NEW_ARRAY

**TASK:** call the function 'multiple_matrix_addition' with matrix [A,A,B,B,B] as input


In [29]:
multiple_matrix_addition([A,A,B,B,B])

array([[12., 17.],
       [22., 27.]])

**TASK:** 

In [34]:
def can_multiply(array_a: np.ndarray, array_b: np.ndarray) -> bool:
    """
    Define function 'can_multiply' that checks if two arrays (matrices) can be multiplied

    PARAMS:
        array_a (numpy.ndarray) - first array
        array_b (numpy.ndarray) - second array
    RETURN:
        True - if arrays can be multiplied, also print the shape of the new array
        False - if arrays can not be multiplied, also print 'Matrices can not be multiplied.'
    """
    if array_a.shape[1] == array_b.shape[0]:
        print((array_a.shape[0], array_b.shape[1]))
        return array_a.shape[1] == array_b.shape[0]

    print('Matrices cannot be multiplied.')
    return array_a.shape[1] == array_b.shape[0]

**TASK:** call the function 'can_multiply' with matrix 'A' and 'B' as inputs

In [35]:
can_multiply(A, B)

(2, 2)


True

**TASK:**  define matrix (3 x 2) matrix C

In [36]:
C = np.arange(1, 7).reshape(3,2)
C

array([[1, 2],
       [3, 4],
       [5, 6]])

**TASK:**  call the function 'can_multiply' with matrix 'A' and 'C' as inputs

In [37]:
can_multiply(A, C)

Matrices cannot be multiplied.


False

**TASK:**  call the function 'can_multiply' with matrix 'C' and 'A' as inputs (now C,A not A,C). Do you know why is the result different?

This works because matrix multiplication is not commutative:
$$\bm{AC} \neq \bm{CA}$$
C has the same number of columns as A has rows, therefore a dot product can be obtained.

In [38]:
can_multiply(C, A)

(3, 2)


True

**TASK:** 

In [39]:
def matrix_multiplication(array_a: np.ndarray, array_b: np.ndarray) -> np.ndarray:
    """
    Define function 'matrix_multiplication' that multiply two numpy.ndarrays

    PARAMS:
    array_a (numpy.ndarray) - first array
    array_b (numpy.ndarray) - second array
    RETURN:
        NEW_ARRAY (numpy.ndarray) - new A * B array
        
    Do not forget to check if two matrices can be multiplied.

    """
    if can_multiply(array_a, array_b):
        return array_a.dot(array_b)

**TASK:**  call the function 'matrix_multiplication' with matrix 'C' and 'B' 


In [41]:
matrix_multiplication(C, B)

(3, 2)


array([[16, 19],
       [36, 43],
       [56, 67]])

**TASK:** call the function 'matrix_multiplication' with matrix 'A' and 'C' 

In [43]:
matrix_multiplication(A, C)

Matrices cannot be multiplied.
