# NumPy exercises

We are going to practice NumPy skills and basic syntax.

We put here also some examples that were not in the tutorial on purpose. Try to use google and offial NumPy documentation to solve these exercises.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 3. Create a null vector of size 10 (★☆☆)

In [2]:
null_vector = np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [3]:
null_vector[4] = 1
null_vector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [4]:
vector = np.arange(10,50)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [5]:
vector[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [6]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [7]:
[index for index, value in enumerate(np.array([1,2,0,0,4,0])) if value != 0]

[0, 1, 4]

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [8]:
np.random.rand(3, 3, 3)

array([[[0.72657829, 0.82523439, 0.82867774],
        [0.33100501, 0.15389608, 0.44901434],
        [0.298697  , 0.70417692, 0.00533128]],

       [[0.54095012, 0.34656235, 0.20405265],
        [0.29603934, 0.30846935, 0.1823443 ],
        [0.49668778, 0.458265  , 0.22485045]],

       [[0.36809371, 0.62180664, 0.81278522],
        [0.71771882, 0.49009976, 0.30288723],
        [0.66058434, 0.80302798, 0.42554246]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [9]:
a = np.random.rand(10, 10)
print(a)
print(a.max())
print(a.min())

[[0.90668102 0.63184086 0.28825015 0.13050789 0.91402443 0.53564416
  0.18055296 0.80731522 0.76873864 0.04246132]
 [0.10449753 0.68683318 0.56359618 0.53545764 0.47499631 0.6686034
  0.37526989 0.8567583  0.23083109 0.17846766]
 [0.55219103 0.54526715 0.36639102 0.16371757 0.93886393 0.31641417
  0.60839234 0.03102418 0.42018171 0.29333627]
 [0.05254381 0.84345409 0.062367   0.04946552 0.21659716 0.450617
  0.21755786 0.11396459 0.27281459 0.95191849]
 [0.37514541 0.3346992  0.21959708 0.11507735 0.01437362 0.49538825
  0.04782702 0.94420319 0.13849044 0.78551597]
 [0.98727256 0.26617813 0.96873954 0.889045   0.36783895 0.08340259
  0.84738515 0.46336405 0.49342504 0.84046134]
 [0.80755573 0.18743108 0.11356663 0.06823452 0.10384007 0.48064891
  0.33189394 0.95975501 0.28237058 0.12931827]
 [0.33748868 0.19902791 0.27002786 0.30685809 0.51963805 0.90754231
  0.84499042 0.0328689  0.01873189 0.29085137]
 [0.2177781  0.74338205 0.56765335 0.5380455  0.65594686 0.84233757
  0.17659224 0.

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [10]:
a = np.random.rand(30)
print(a, a.mean())

[0.4155329  0.82166729 0.7620972  0.18733497 0.18026512 0.23940754
 0.56027221 0.88008534 0.17149179 0.47034908 0.86154091 0.51846652
 0.04287223 0.36377638 0.87869259 0.91851179 0.02726485 0.66029262
 0.12122682 0.07426405 0.55831037 0.03935266 0.7211344  0.33783878
 0.42567611 0.22445213 0.66731981 0.15827865 0.66407424 0.89729888] 0.4616382743554686


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [11]:
a = np.ones([3,3])
a[1, 1] = 0
a

array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [12]:
def zero_border(array: np.array) -> np.array:
    """
    Generate a zeros border array using the shape of the input array, place the input within the border array and return the result.
    """
    zeros = np.zeros([value+2 for value in array.shape])
    zeros[1:-1, 1:-1] = array
    return zeros

In [13]:
zero_border(a)

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 0., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [21]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [15]:
matrix = np.zeros((5,5))
target = [1, 2, 3, 4]
matrix[[value for value in target], [index for index in range(len(target))]] = target
matrix

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [146]:
array = np.random.rand(6,7,8)
print(array.flat[100])

np.unravel_index(100, (6,7,8))
array[1,5,4]


0.36269073760553683


0.36269073760553683

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [30]:
array = np.random.rand(5,5)

def normalize_array(array: np.array):
    return (array - array.min())/(array.max() - array.min())

normalize_array(array)

array([[0.01788721, 0.54649913, 0.17830425, 1.        , 0.00598786],
       [0.78390721, 0.95849495, 0.96546962, 0.31613665, 0.8778332 ],
       [0.39993079, 0.76444611, 0.        , 0.51546836, 0.53085634],
       [0.19334667, 0.33829661, 0.97641485, 0.58882777, 0.61637964],
       [0.31367132, 0.88963525, 0.16797824, 0.36033408, 0.48454717]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [40]:
array_1d = np.arange(0, 10)

array_1d[(array_1d > 3) & (array_1d < 8)] *= -1
array_1d

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9])

#### 29. How to round away from zero a float array ? (★☆☆)

In [43]:
# ceil will work here except for negative numbers, which will round closer to 0.
unrounded = np.random.rand(3,3)
print(unrounded)
print(np.ceil(unrounded))

[[0.45309717 0.74804327 0.64327309]
 [0.78439382 0.29401217 0.55781879]
 [0.04385825 0.85222497 0.60238824]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


#### 30. How to find common values between two arrays? (★☆☆)

In [45]:
array_1 = np.arange(5, 16)
array_2 = np.arange(0, 11)
np.intersect1d(array_1, array_2)

array([ 5,  6,  7,  8,  9, 10])

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [47]:
np.sqrt(-1) == np.emath.sqrt(-1)

M:\Python\Anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [56]:
np.array(tuple((integer for integer in range(10))))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [59]:
np.random.rand(10)

array([0.04061104, 0.37422564, 0.65352629, 0.47464583, 0.6805699 ,
       0.11848583, 0.65778577, 0.19395381, 0.37971838, 0.96484952])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [66]:
array = np.random.rand(10)
array.sort()
print(array)

[0.06844486 0.09411602 0.47424147 0.55457788 0.60505565 0.6432897
 0.84957666 0.8755833  0.89344265 0.95420431]


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [70]:
array_a = np.random.rand(10)
array_b = np.random.rand(10)
np.all(array_a == array_b)

False

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [91]:
array = np.random.rand(10)
print(array, array.max())
array[np.where(array == array.max())] = 0
array


[0.71538384 0.10913944 0.98334952 0.05849126 0.95610417 0.3742531
 0.8078321  0.67114536 0.13101873 0.65570569] 0.9833495232694802


array([0.71538384, 0.10913944, 0.        , 0.05849126, 0.95610417,
       0.3742531 , 0.8078321 , 0.67114536, 0.13101873, 0.65570569])

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [92]:
scalar = 0.5
array = np.random.rand(10)
print(array)

diff_array = np.abs(array - scalar)
print(diff_array)

index = diff_array.argmin()
print(f"Closest value is {array[index]}")

[0.04235709 0.76703552 0.11077068 0.92328252 0.04026066 0.71132671
 0.46079041 0.24080791 0.60610597 0.6577063 ]
[0.45764291 0.26703552 0.38922932 0.42328252 0.45973934 0.21132671
 0.03920959 0.25919209 0.10610597 0.1577063 ]
Closest value is 0.4607904104115058


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [212]:
x = np.random.rand(10)*10
x.astype(np.int32)


array([8, 3, 0, 5, 0, 8, 2, 2, 9, 2])

#### 59. How to sort an array by the nth column? (★★☆)

In [158]:
array = np.random.rand(9).reshape(3,3)

def sort_nth_col(array: np.array, column: int) -> np.array:
    return array[array[:,column].argsort()]

sort_nth_col(array, 2)

array([[0.51639863, 0.57066759, 0.02847423],
       [0.30696622, 0.89361308, 0.72154386],
       [0.17152166, 0.68527698, 0.83389686]])

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [240]:
array = np.random.randint(0,2, (5, 20))
print(array)
(~array.any(axis=0)).any()

[[1 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 1 0 0]
 [0 1 1 0 0 1 1 0 0 1 0 1 1 0 1 0 0 0 0 1]
 [0 0 0 1 0 0 1 1 0 1 1 0 0 0 1 0 0 1 0 1]
 [1 0 1 1 0 0 0 0 1 0 1 0 1 1 0 0 1 0 0 0]
 [1 1 0 0 1 0 1 0 1 0 1 1 0 1 1 0 1 0 1 1]]


True

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [184]:
vector = [1, 2, 3, 4, 5, 6, 7]

def add_zeros(vector: np.array) -> np.array:
    """Add 3 consecutive 0s between each vector entry."""
    x = len(vector)
    # 3 zeros added for each index in the vector except the last, plus enough indices for the original values.
    zeros_size = (x-1)*3 + x
    zeros = np.zeros(zeros_size, dtype=int)
    zeros[::4] = vector
    return zeros

add_zeros(vector)

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5, 0, 0, 0, 6, 0,
       0, 0, 7])

#### 72. How to swap two rows of an array? (★★★)

In [190]:
array = np.arange(0, 6).reshape(2,3)
array[[0, 1]] = array[[1, 0]]
array

array([[3, 4, 5],
       [0, 1, 2]])

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [198]:
array = np.negative(np.random.rand(10))
print(array)

np.logical_not(1 > 2)

[-0.55166585 -0.71053814 -0.67527885 -0.69456466 -0.34245677 -0.41239056
 -0.23979097 -0.96883598 -0.28855701 -0.14731161]


True

#### 83. How to find the most frequent value in an array?

In [215]:
array = np.random.randint(1, 10, size=100)
print(array)

values, counts = np.unique(array, return_counts=True)
index = np.argmax(counts)
print(counts, values)
values[index]


[5 6 9 7 4 7 4 4 4 4 2 8 1 2 8 9 4 5 1 5 8 2 1 4 2 5 4 1 1 5 8 5 5 6 9 5 6
 7 4 4 5 4 7 7 1 5 6 1 7 2 5 9 6 5 9 9 5 6 5 5 8 1 2 5 4 6 1 9 1 1 9 3 6 3
 6 2 4 4 5 1 2 3 4 4 7 8 5 3 9 8 8 6 5 6 3 2 7 2 3 2]
[12 11  6 16 19 11  8  8  9] [1 2 3 4 5 6 7 8 9]


5

#### 89. How to get the n largest values of an array (★★★)

In [218]:
array = np.random.randint(1, 1000, size=100)

def get_n_largest(array: np.array, n: int) -> np.array:
    indices = np.argpartition(array, -n)[-n:]
    return array[indices]

print(array)
get_n_largest(array, 5)

[270 613 517 248 680 409 718 545 236 188 815 378 804 216 722 153  17  32
 276 522 644 139 970 181 306 581 119 261  47 359  26 591 576 268 208  19
 571 139 966  85 863 207 245 271 314 390 918 563 179 471 174 234 913 112
 749 269 230 909 872 578 539 965 605 524 138 905 619 775 344  70 423 206
 550 221 480 719 798 823 419 178   3 407  49 795 841 702 948 669 613  48
 770 177  79 724 814 629 760  82 374 968]


array([948, 965, 966, 970, 968])

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [225]:
array = np.zeros((5, 5))
array[0, 1] = 2
array[3, 2] = 1

print(array)

np.unique(array, axis=0)


[[0. 2. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]]


array([[0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 2., 0., 0., 0.]])