# **Vector and Matrix Operations**
---
An inexhaustive list of common NumPy functions and methods.

In [1]:
import numpy as np

## **Representation**
---

In text, ***vectors*** (1D arrays) are typically represented as lowercase bold Roman letters (e.g. $\bm{v}$) when representing data or as lowercase bold Greek letters (e.g. $\bm{\omega}$) when representing parameters.

In [2]:
# create a vector
v = np.array([1, 2, 3, 4])
v

array([1, 2, 3, 4])

In text, ***matrices*** (2D arrays) are typically represented as uppercase bold Roman letters (e.g. $\bm{A}$) when representing data or as uppercase bold Roman letters (e.g. $\bm{\Omega}$) when representing parameters.

In [3]:
# create a matrix
A = np.array([[1,2],[3,4],[5,6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
# Both are numpy ndarrays with appropriate dimensions.
print(type(v), type(A))
print(v.shape, A.shape)

<class 'numpy.ndarray'> <class 'numpy.ndarray'>
(4,) (3, 2)


## **Transposition**
---

In text, the transpose of a matrix ($\bm{A}$) is typically denoted with a superscript, uppercase T ($\bm{A}^{T}$); however, a prime symbol ( $^{\prime}$ ) can also be used ( e.g. $\bm{A}^{\prime}$ )

In [5]:
# Transpose matrix (rows and columns are swapped)
A_T1 = A.T
A_T2 = A.transpose()

print(A_T1 == A_T2)

[[ True  True  True]
 [ True  True  True]]


## **Addition**
---

Scalars can be added to matrices with numpy through ***broadcasting***, i.e. the scalar is converted into an array of the same shape as the matrix it is added to.

In [6]:
print(A)
# Add 5 to each value of A.
print(A + 5)

[[1 2]
 [3 4]
 [5 6]]
[[ 6  7]
 [ 8  9]
 [10 11]]


Broadcasting can be applied to arrays as well, but only if the first array has the same number of rows as the second and one of the arrays has a single column only.

In [7]:
# This works
B = np.array([[2], [4], [3]])

print(A + B)

[[3 4]
 [7 8]
 [8 9]]


In [8]:
# This does not
# This works
B = np.array([[2], [4]])

print(A + B)

ValueError: operands could not be broadcast together with shapes (3,2) (2,1) 

## **Multiplication**
---

The number of columns of the first matrix must be equal to the number of rows of the second one. If the dimensions of the first matrix are (m×n), the second matrix needs to be of shape (n×o). The resulting matrix (referred to as the ***dot product***) will have the shape (m×o).

The dot product is *not* commutative! That is:  
$$\bm{AB} \neq \bm{BA}$$

In [9]:
# 3x2 matrix
A = np.array([[1, 2], [3, 4], [5, 6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
# 2x1 matrix
B = np.array([[2], [4]])
B

array([[2],
       [4]])

In [11]:
# dot can be called off of an array onto another
A_B = A.dot(B)
A_B

array([[10],
       [22],
       [34]])

In [12]:
# or dot can be called on two arrays with the same resulting 3x1 matrix.
A_B = np.dot(A, B)
A_B

array([[10],
       [22],
       [34]])

```python



## **Identity Matrices**
---

An identity matrix $\bm{I}_{n}$ is a special square (nxn) matrix which has 1s on the main diagonal and 0s everywhere else.

In [13]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

The dot product of an identity matrix with another matrix is the same matrix! Thus, for this special case the commutative property holds:
$$\bm{AI} = \bm{IA}$$

In [14]:
IA = I.dot(A)
AI = A.dot(I)

print(IA == AI)
AI

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

## **Determinants**
---

Determinants can be computed for square matrices using the `numpy.linalg` module.

In [15]:
# Create a matrix.
M = np.array([[1,2],[3,4]])
M

array([[1, 2],
       [3, 4]])

In [16]:
# Compute the determinant.
det_M = np.linalg.det(M)
det_M

-2.0000000000000004

In [17]:
# LinAlgError if the matrix is not square
F = np.array([[1,2],[3,4],[5,6]])
det_F = np.linalg.det(F)
det_F

LinAlgError: Last 2 dimensions of the array must be square

## **Inverse Matrices**
---

The inverse matrix of $\bm{A}$ with shape (nxn) is $\bm{A}^{-1}$ such that: 

$$\bm{AA}^{-1} = \bm{I}_{n}$$  

In [18]:
# Create 3x3 matrix
A = np.array([[3, 0, 2], [2, 0, -2], [0, 1, 1]])
A

array([[ 3,  0,  2],
       [ 2,  0, -2],
       [ 0,  1,  1]])

In [19]:
# Compute the inverse of A
A_inv = np.linalg.inv(A)
A_inv

array([[ 0.2,  0.2,  0. ],
       [-0.2,  0.3,  1. ],
       [ 0.2, -0.3, -0. ]])

In [20]:
# Confirm the inverse relationship.
I = A_inv.dot(A)
I

array([[ 1.00000000e+00,  0.00000000e+00, -1.11022302e-16],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])