# **Vector and Matrix Operations**
---

In [1]:
import numpy as np

## **1) Representation**
---

In text, ***vectors*** (1D arrays) are typically represented as lowercase bold Roman letters (e.g. $\bm{v}$) when representing data or as lowercase bold Greek letters (e.g. $\bm{\omega}$) when representing parameters.

In [3]:
# create a vector
v = np.array([1, 2, 3, 4])
v

array([1, 2, 3, 4])

In text, ***matrices*** (2D arrays) are typically represented as uppercase bold Roman letters (e.g. $\bm{A}$) when representing data or as uppercase bold Roman letters (e.g. $\bm{\Omega}$) when representing parameters.

In [4]:
# create a matrix
A = np.array([[1,2],[3,4],[5,6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
# Both are numpy ndarrays with appropriate dimensions.
print(type(v), type(A))
print(v.shape, A.shape)

<class 'numpy.ndarray'> <class 'numpy.ndarray'>
(4,) (3, 2)


## **2) Transposition**
---

In text, the transpose of a matrix ($\bm{A}$) is typically denoted with a superscript, uppercase T ($\bm{A}$<sup>T</sup>); however, a prime symbol ( <sup>$\prime$</sup> ) can also be used ( e.g. $\bm{A}$<sup>$\prime$</sup> )

In [10]:
# Transpose matrix (rows and columns are swapped)
A_T1 = A.T
A_T2 = A.transpose()

print(A_T1 == A_T2)

[[ True  True  True]
 [ True  True  True]]


## **3) Addition**
---

Scalars can be added to matrices with numpy through ***broadcasting***, i.e. the scalar is converted into an array of the same shape as the matrix it is added to.

In [13]:
print(A)
# Add 5 to each value of A.
print(A + 5)

[[1 2]
 [3 4]
 [5 6]]
[[ 6  7]
 [ 8  9]
 [10 11]]


Broadcasting can be applied to arrays as well, but only if the first array has the same number of rows as the second and one of the arrays has a single column only.

In [16]:
# This works
B = np.array([[2], [4], [3]])

print(A + B)

[[3 4]
 [7 8]
 [8 9]]


In [17]:
# This does not
# This works
B = np.array([[2], [4]])

print(A + B)

ValueError: operands could not be broadcast together with shapes (3,2) (2,1) 

## **4) Multiplication**
---
*Dot product*

```python

