# **NumPy**
---

- NumPy arrays are statically typed (not type checking necessary), unlike python lists, and more memory efficient. 
- NumPy arrays are allocated in contiguous blocks of memory, which CPU architecture is optimized to use more efficiently than referencing different locations in memory (each of these different locations requires an additional instruction whereas contiguous blocks take advantage of Single Instruction Multiple Data **(SIMD)** vector processing).

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
b= np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [5]:
# number of dimensions
a.ndim

1

In [6]:
# shape of array (rows, cols)
b.shape

(2, 3)

In [7]:
# data type
a.dtype

dtype('int32')

In [8]:
a.itemsize

4

In [9]:
a.nbytes

12

In [15]:
c = np.arange(1, 15).reshape(2,7)
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [16]:
# indexing is [row, column]
c[1, 5]

13

In [17]:
# get first row
c[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [18]:
# get third column
c[:, 2]

array([ 3, 10])

In [24]:
# 3D array.
d = np.arange(1, 9).reshape(2, 2, 2)
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [25]:
# retrieve 6
d[1,0,1]

6

In [27]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [29]:
np.full((3,3), 7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [33]:
np.random.rand(4, 2, 3)

array([[[0.24987508, 0.68975556, 0.61831967],
        [0.63340238, 0.63968364, 0.88892773]],

       [[0.87271079, 0.03784687, 0.1584237 ],
        [0.64165814, 0.79909354, 0.99080524]],

       [[0.81785096, 0.05858531, 0.98770044],
        [0.16138957, 0.90530452, 0.85706274]],

       [[0.76929974, 0.74431401, 0.37936513],
        [0.6723377 , 0.2121472 , 0.7155243 ]]])

In [37]:
np.random.random_sample(5)

array([0.70646479, 0.00728956, 0.58900507, 0.43856205, 0.84355214])

In [38]:
np.random.randint(9, size=(3,3))

array([[1, 1, 1],
       [4, 4, 2],
       [5, 1, 7]])

In [42]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [47]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1, 1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [48]:
# be sure to use the array.copy() method if a duplicate array is needed rather than a reference
a = np.arange(1, 9)
b = a
b[0] = 100
print(b)
print(a)

[100   2   3   4   5   6   7   8]
[100   2   3   4   5   6   7   8]


In [49]:
a = np.arange(1, 9)
b = a.copy()
b[0] = 100
print(b)
print(a)

[100   2   3   4   5   6   7   8]
[1 2 3 4 5 6 7 8]


Basic math operators can be applied to arrays as well.

In [52]:
stats = np.arange(1, 13).reshape(3,4)
print(stats)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [59]:
print(stats.mean())
print(stats.min())
print(stats.max())

6.5
1
12


In [60]:
stats > 6

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])